name: Release Beta

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Get PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            BRANCH_NAME="${GITHUB_REF##*/}"
            PR_NUMBER=$(gh pr list --state open --json headRefName,number | jq -r ".[] | select(.headRefName==\"$BRANCH_NAME\") | .number")
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Get build count
        id: buildcount
        run: |
          COUNT=$(git tag --list "*-beta${{ github.event.pull_request.number || github.ref_name }}.*" | wc -l)
          echo "BUILD_COUNT=$((COUNT+1))" >> $GITHUB_ENV

      - name: Release beta
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          BUILD_COUNT: ${{ env.BUILD_COUNT }}
        run: npx semantic-release
